//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fit.Common {
    
    public partial class MessagePanel {
        protected System.Web.UI.WebControls.Panel pnlMessage;
        protected System.Web.UI.WebControls.Label lblMessage;
    }
}
