//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Default", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abreviação.
        /// </summary>
        internal static string ABBREVIATION {
            get {
                return ResourceManager.GetString("ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        internal static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Anexos.
        /// </summary>
        internal static string ADD_ANEXOS {
            get {
                return ResourceManager.GetString("ADD_ANEXOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Add.jpg.
        /// </summary>
        internal static string ADD_IMAGE {
            get {
                return ResourceManager.GetString("ADD_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Todos(as) --.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos Projetos.
        /// </summary>
        internal static string ALL_PROJECTS {
            get {
                return ResourceManager.GetString("ALL_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um item cadastrado com esta descrição..
        /// </summary>
        internal static string ALREADY_EXISTS_THIS_DESCRIPTION {
            get {
                return ResourceManager.GetString("ALREADY_EXISTS_THIS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail deste usuário já foi cadastrado.
        /// </summary>
        internal static string ALREADY_EXISTS_THIS_EMAIL {
            get {
                return ResourceManager.GetString("ALREADY_EXISTS_THIS_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexos.
        /// </summary>
        internal static string ANEXOS {
            get {
                return ResourceManager.GetString("ANEXOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site / BU Lead.
        /// </summary>
        internal static string BULEAD {
            get {
                return ResourceManager.GetString("BULEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Cancel.jpg.
        /// </summary>
        internal static string CANCEL_IMAGE {
            get {
                return ResourceManager.GetString("CANCEL_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capex should be approved for saving the project in Develop and Deploy stage.
        /// </summary>
        internal static string CAPEX_APPROVAL {
            get {
                return ResourceManager.GetString("CAPEX_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Issued Date.
        /// </summary>
        internal static string CAPEX_DATE {
            get {
                return ResourceManager.GetString("CAPEX_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar fase de Definir a Desenvolver.
        /// </summary>
        internal static string CAPEX_PO_APPROVAL {
            get {
                return ResourceManager.GetString("CAPEX_PO_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluídos.
        /// </summary>
        internal static string CLOSED {
            get {
                return ResourceManager.GetString("CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de finalização.
        /// </summary>
        internal static string CLOSED_DATE {
            get {
                return ResourceManager.GetString("CLOSED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de conclusão.
        /// </summary>
        internal static string COMMIT_DATE {
            get {
                return ResourceManager.GetString("COMMIT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the cost saving is greater than US$.
        /// </summary>
        internal static string COSTSAVING_ALERTMESSAGE_PART1 {
            get {
                return ResourceManager.GetString("COSTSAVING_ALERTMESSAGE_PART1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Are you sure you want to continue?.
        /// </summary>
        internal static string COSTSAVING_ALERTMESSAGE_PART2 {
            get {
                return ResourceManager.GetString("COSTSAVING_ALERTMESSAGE_PART2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Justification.
        /// </summary>
        internal static string COST_SAVING {
            get {
                return ResourceManager.GetString("COST_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned savings should equal the sum of itemized savings (HC savings + Throughput savings + … etc) from your ROI tool.
        /// </summary>
        internal static string COST_SAVING_MATCH {
            get {
                return ResourceManager.GetString("COST_SAVING_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one Automation Saving Type.
        /// </summary>
        internal static string COST_SAVING_MSG {
            get {
                return ResourceManager.GetString("COST_SAVING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Justification is required before closing the Automation Project.
        /// </summary>
        internal static string COST_SAVING_REQUIRED {
            get {
                return ResourceManager.GetString("COST_SAVING_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Localização.
        /// </summary>
        internal static string CO_LOCATIONS {
            get {
                return ResourceManager.GetString("CO_LOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AME-Co-Resp..
        /// </summary>
        internal static string CO_RESPONSIBLE {
            get {
                return ResourceManager.GetString("CO_RESPONSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inferior a Data de Criação..
        /// </summary>
        internal static string DATA_INF_OPEN_DATE {
            get {
                return ResourceManager.GetString("DATA_INF_OPEN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inferior a data inicial.
        /// </summary>
        internal static string DATA_INF_START_DATE {
            get {
                return ResourceManager.GetString("DATA_INF_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DATE_HEADER {
            get {
                return ResourceManager.GetString("DATE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data é obrigatória..
        /// </summary>
        internal static string DATE_REQUIRED {
            get {
                return ResourceManager.GetString("DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao tentar excluir este registro..
        /// </summary>
        internal static string DELETED_ERROR {
            get {
                return ResourceManager.GetString("DELETED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído com sucesso..
        /// </summary>
        internal static string DELETED_SUCESS {
            get {
                return ResourceManager.GetString("DELETED_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Você realmente deseja excluir este projeto?&apos;);.
        /// </summary>
        internal static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Delete.jpg.
        /// </summary>
        internal static string DELETE_IMAGE {
            get {
                return ResourceManager.GetString("DELETE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Projeto.
        /// </summary>
        internal static string DETAIL_PROJECT {
            get {
                return ResourceManager.GetString("DETAIL_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Edit.jpg.
        /// </summary>
        internal static string EDIT_IMAGE {
            get {
                return ResourceManager.GetString("EDIT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        internal static string ENDDATE {
            get {
                return ResourceManager.GetString("ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemplos de Cost Saving ou Avoidance.
        /// </summary>
        internal static string EXAMPLE_OF_COST_SAVINGS {
            get {
                return ResourceManager.GetString("EXAMPLE_OF_COST_SAVINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do arquivo excedeu à 2MB..
        /// </summary>
        internal static string EXPECTED_SIZE_MAX {
            get {
                return ResourceManager.GetString("EXPECTED_SIZE_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9]+[,][0-9]*[0-9]*.
        /// </summary>
        internal static string EXPRESSION_NUMBER {
            get {
                return ResourceManager.GetString("EXPRESSION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número máximo de arquivos permitidos já foi inserido..
        /// </summary>
        internal static string FILE_COUNT_EXCEEDED {
            get {
                return ResourceManager.GetString("FILE_COUNT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        internal static string FILTER {
            get {
                return ResourceManager.GetString("FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar por.
        /// </summary>
        internal static string FILTER_BY {
            get {
                return ResourceManager.GetString("FILTER_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar Filtro.
        /// </summary>
        internal static string FILTER_HIDDEN {
            get {
                return ResourceManager.GetString("FILTER_HIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro ....
        /// </summary>
        internal static string FILTER_SHOW {
            get {
                return ResourceManager.GetString("FILTER_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Finish.jpg.
        /// </summary>
        internal static string FINISH_IMAGE {
            get {
                return ResourceManager.GetString("FINISH_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD/MM/YYYY.
        /// </summary>
        internal static string FORMAT_DATE {
            get {
                return ResourceManager.GetString("FORMAT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato Inválido.
        /// </summary>
        internal static string FORMAT_INVALID {
            get {
                return ResourceManager.GetString("FORMAT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar Relatório.
        /// </summary>
        internal static string GENERATE_REPORT {
            get {
                return ResourceManager.GetString("GENERATE_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos.
        /// </summary>
        internal static string GET_ALL {
            get {
                return ResourceManager.GetString("GET_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        internal static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao tentar inserir este registro..
        /// </summary>
        internal static string INSERTED_ERROR {
            get {
                return ResourceManager.GetString("INSERTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro inserido com sucesso..
        /// </summary>
        internal static string INSERTED_SUCESS {
            get {
                return ResourceManager.GetString("INSERTED_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Insert.jpg.
        /// </summary>
        internal static string INSERT_IMAGE {
            get {
                return ResourceManager.GetString("INSERT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para inserir um registro clique no botão abaixo..
        /// </summary>
        internal static string INSERT_NEW_PROJECT {
            get {
                return ResourceManager.GetString("INSERT_NEW_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo inválido.
        /// </summary>
        internal static string INVALID_FILE {
            get {
                return ResourceManager.GetString("INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin..
        /// </summary>
        internal static string IS_ADMIN {
            get {
                return ResourceManager.GetString("IS_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Login.
        /// </summary>
        internal static string LAST_LOGIN {
            get {
                return ResourceManager.GetString("LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        internal static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/New.jpg.
        /// </summary>
        internal static string NEW_IMAGE {
            get {
                return ResourceManager.GetString("NEW_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir um novo item.
        /// </summary>
        internal static string NEW_ITEM {
            get {
                return ResourceManager.GetString("NEW_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Next.jpg.
        /// </summary>
        internal static string NEXT_IMAGE {
            get {
                return ResourceManager.GetString("NEXT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum projeto foi encontrado para o filtro selecionado. \nPor favor altere o filtro e tente novamente..
        /// </summary>
        internal static string NOPROJECTS {
            get {
                return ResourceManager.GetString("NOPROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe mas você não possue permissão para acessar o sistema. Favor contatar o administrador do sistema..
        /// </summary>
        internal static string NOT_ACCESS {
            get {
                return ResourceManager.GetString("NOT_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criados.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        internal static string OPEN_DATE {
            get {
                return ResourceManager.GetString("OPEN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros Responsibles.
        /// </summary>
        internal static string OTHERS_RESPONSIBLES {
            get {
                return ResourceManager.GetString("OTHERS_RESPONSIBLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        internal static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progresso %.
        /// </summary>
        internal static string PERCENT_COMPLETION {
            get {
                return ResourceManager.GetString("PERCENT_COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo.
        /// </summary>
        internal static string PERIOD {
            get {
                return ResourceManager.GetString("PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO should be issued for saving the project in Develop and Deploy stage.
        /// </summary>
        internal static string PO_APPROVAL {
            get {
                return ResourceManager.GetString("PO_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Previous.jpg.
        /// </summary>
        internal static string PREVIOUS_IMAGE {
            get {
                return ResourceManager.GetString("PREVIOUS_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto.
        /// </summary>
        internal static string PROJECT {
            get {
                return ResourceManager.GetString("PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um documento relacionado ao registro a ser excluído,  portanto esta operação foi cancelada..
        /// </summary>
        internal static string RECORD_RELATION_DELETE {
            get {
                return ResourceManager.GetString("RECORD_RELATION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um documento relacionado ao registro a ser atualizado, portanto esta operação foi cancelada..
        /// </summary>
        internal static string RECORD_RELATION_UPDATE {
            get {
                return ResourceManager.GetString("RECORD_RELATION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região.
        /// </summary>
        internal static string REGION {
            get {
                return ResourceManager.GetString("REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Regiões.
        /// </summary>
        internal static string REGION_CODE {
            get {
                return ResourceManager.GetString("REGION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string REMARKS {
            get {
                return ResourceManager.GetString("REMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Remove.jpg.
        /// </summary>
        internal static string REMOVE_IMAGE {
            get {
                return ResourceManager.GetString("REMOVE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string REPORT_TYPE {
            get {
                return ResourceManager.GetString("REPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final obrigatória.
        /// </summary>
        internal static string REQUIRED_END_DATE {
            get {
                return ResourceManager.GetString("REQUIRED_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial obrigatória.
        /// </summary>
        internal static string REQUIRED_START_DATE {
            get {
                return ResourceManager.GetString("REQUIRED_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        internal static string RESPONSIBLE {
            get {
                return ResourceManager.GetString("RESPONSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsáveis.
        /// </summary>
        internal static string RESPONSIBLES {
            get {
                return ResourceManager.GetString("RESPONSIBLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string REVENUE {
            get {
                return ResourceManager.GetString("REVENUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue / Cost Saving.
        /// </summary>
        internal static string REVENUE_COSTSAVING {
            get {
                return ResourceManager.GetString("REVENUE_COSTSAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Save.jpg.
        /// </summary>
        internal static string SAVE_IMAGE {
            get {
                return ResourceManager.GetString("SAVE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria da Economia.
        /// </summary>
        internal static string SAVINGCATEGORY {
            get {
                return ResourceManager.GetString("SAVINGCATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Economia.
        /// </summary>
        internal static string SAVING_AMOUNT {
            get {
                return ResourceManager.GetString("SAVING_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da Economia $USD.
        /// </summary>
        internal static string SAVING_AMOUNT_HEADER {
            get {
                return ResourceManager.GetString("SAVING_AMOUNT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da Economia inválido..
        /// </summary>
        internal static string SAVING_AMOUNT_INVALID {
            get {
                return ResourceManager.GetString("SAVING_AMOUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da Economia é obrigatório..
        /// </summary>
        internal static string SAVING_AMOUNT_REQUIRED {
            get {
                return ResourceManager.GetString("SAVING_AMOUNT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria de Economia.
        /// </summary>
        internal static string SAVING_CATEGORY {
            get {
                return ResourceManager.GetString("SAVING_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria de Economia.
        /// </summary>
        internal static string SAVING_CATEGORY_HEADER {
            get {
                return ResourceManager.GetString("SAVING_CATEGORY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria de Economia é obrigatório..
        /// </summary>
        internal static string SAVING_CATEGORY_REQUIRED {
            get {
                return ResourceManager.GetString("SAVING_CATEGORY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Economia.
        /// </summary>
        internal static string SAVING_TYPE {
            get {
                return ResourceManager.GetString("SAVING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Economia.
        /// </summary>
        internal static string SAVING_TYPE_HEADER {
            get {
                return ResourceManager.GetString("SAVING_TYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Economia é obrigatório..
        /// </summary>
        internal static string SAVING_TYPE_REQUIRED {
            get {
                return ResourceManager.GetString("SAVING_TYPE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar projetos.
        /// </summary>
        internal static string SEARCH_PROJECT {
            get {
                return ResourceManager.GetString("SEARCH_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmento.
        /// </summary>
        internal static string SEGMENT {
            get {
                return ResourceManager.GetString("SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        internal static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um item.
        /// </summary>
        internal static string SELECT_A_ITEM {
            get {
                return ResourceManager.GetString("SELECT_A_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Para selecionar mais de um, use Control / Shift).
        /// </summary>
        internal static string SELECT_MANY_LISTBOX {
            get {
                return ResourceManager.GetString("SELECT_MANY_LISTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlSiteMapProviderPT.
        /// </summary>
        internal static string SITEMAPKEY {
            get {
                return ResourceManager.GetString("SITEMAPKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Code.
        /// </summary>
        internal static string SITE_CODE {
            get {
                return ResourceManager.GetString("SITE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        internal static string STARTDATE {
            get {
                return ResourceManager.GetString("STARTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Categoria.
        /// </summary>
        internal static string TITLE_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Clientes.
        /// </summary>
        internal static string TITLE_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Exceções de E-mail.
        /// </summary>
        internal static string TITLE_EMAIL_EXCEPTIONS {
            get {
                return ResourceManager.GetString("TITLE_EMAIL_EXCEPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Localização.
        /// </summary>
        internal static string TITLE_LOCATION {
            get {
                return ResourceManager.GetString("TITLE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Projetos.
        /// </summary>
        internal static string TITLE_PROJECTS {
            get {
                return ResourceManager.GetString("TITLE_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Responsáveis.
        /// </summary>
        internal static string TITLE_RESPONSIBLES {
            get {
                return ResourceManager.GetString("TITLE_RESPONSIBLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Saving Categorie.
        /// </summary>
        internal static string TITLE_SAVING_CATEGORY {
            get {
                return ResourceManager.GetString("TITLE_SAVING_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Segmentos.
        /// </summary>
        internal static string TITLE_SEGMENT {
            get {
                return ResourceManager.GetString("TITLE_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Status.
        /// </summary>
        internal static string TITLE_STATUS {
            get {
                return ResourceManager.GetString("TITLE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Usuários.
        /// </summary>
        internal static string TITLE_USERS {
            get {
                return ResourceManager.GetString("TITLE_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adiconar Região.
        /// </summary>
        internal static string TITLE_USER_REGION {
            get {
                return ResourceManager.GetString("TITLE_USER_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem {0} projetos para serem exportados. O sistema não suporta mais que 30 projetos. Por favor altere o range de data e tente novamente..
        /// </summary>
        internal static string TOO_MUCH_PROJECTS {
            get {
                return ResourceManager.GetString("TOO_MUCH_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        internal static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao tentar atualizar este registro..
        /// </summary>
        internal static string UPDATED_ERROR {
            get {
                return ResourceManager.GetString("UPDATED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro alterado com sucesso..
        /// </summary>
        internal static string UPDATED_SUCESS {
            get {
                return ResourceManager.GetString("UPDATED_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD User.
        /// </summary>
        internal static string USERNAME_AD {
            get {
                return ResourceManager.GetString("USERNAME_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este username já foi cadastrado..
        /// </summary>
        internal static string USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido.
        /// </summary>
        internal static string USER_INVALID {
            get {
                return ResourceManager.GetString("USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário X Região.
        /// </summary>
        internal static string USER_REGION {
            get {
                return ResourceManager.GetString("USER_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Projetos.
        /// </summary>
        internal static string VIEW_PROJECTS {
            get {
                return ResourceManager.GetString("VIEW_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-Vindo ao Project Tracker.
        /// </summary>
        internal static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seus Projetos.
        /// </summary>
        internal static string YOUR_PROJECTS {
            get {
                return ResourceManager.GetString("YOUR_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A inserção de projetos somente é permitida por usuários com o perfil de responsável..
        /// </summary>
        internal static string YOU_ARENT_RESPONSIBLE {
            get {
                return ResourceManager.GetString("YOU_ARENT_RESPONSIBLE", resourceCulture);
            }
        }
    }
}
