CREATE TABLE [dbo].[ProjectStageDetail] (
    [ProjectStageDetailId]         BIGINT             IDENTITY (1, 1) NOT NULL,
    [ProjectDetailId]              BIGINT             NOT NULL,
    [EstimatedProjectLife]         INT                NOT NULL,
    [EstimatedProjectCost]         DECIMAL (18)       NOT NULL,
    [IsNewProject]                 BIT                NOT NULL,
    [PlannedPayback]               BIGINT             NULL,
    [ROI]                          DECIMAL (18)       NULL,
    [EvaluationOpenDate]           DATETIMEOFFSET (7) NOT NULL,
    [EvaluationCommitDate]         DATETIMEOFFSET (7) NOT NULL,
    [HeadcountBeforeAutomation]    DECIMAL (18)       NULL,
    [HeadcountAfterAutomation]     DECIMAL (18)       NULL,
    [HeadcountReduction]           DECIMAL (18)       NULL,
    [DefineCommitDate]             DATETIMEOFFSET (7) NULL,
    [SolutionId]                   BIGINT             NOT NULL,
    [ProjectDecisionId]            BIGINT             NOT NULL,
    [IsPOissued]                   BIT                NULL,
    [POissuedate]                  DATETIMEOFFSET (7) NOT NULL,
    [PaidbyId]                     BIGINT             NOT NULL,
    [FATdate]                      DATETIMEOFFSET (7) NOT NULL,
    [SATdate]                      DATETIMEOFFSET (7) NOT NULL,
    [SitedeliveryDate]             DATETIMEOFFSET (7) NOT NULL,
    [PRJNumber]                    VARCHAR (100)      NULL,
    [eCPXnumber]                   VARCHAR (100)      NULL,
    [PaidPercentage]               DECIMAL (18)       NULL,
    [POnumber]                     VARCHAR (100)      NULL,
    [AutomationTypeId]             BIGINT             NOT NULL,
    [IsIPgenerated]                BIT                NOT NULL,
    [BestPractice]                 VARCHAR (500)      NOT NULL,
    [Automationshowcaselink]       VARCHAR (200)      NOT NULL,
    [DroppedReason]                VARCHAR (500)      NOT NULL,
    [Closedate]                    DATETIMEOFFSET (7) NOT NULL,
    [RunningProductionEnvironment] BIT                NOT NULL,
    [RecordStatus]                 CHAR (1)           NOT NULL,
    [CreatedBy]                    BIGINT             NOT NULL,
    [CreatedDate]                  DATETIMEOFFSET (7) NOT NULL,
    [ModifiedBy]                   BIGINT             NOT NULL,
    [ModifiedDate]                 DATETIMEOFFSET (7) NOT NULL,
    PRIMARY KEY CLUSTERED ([ProjectStageDetailId] ASC),
    CONSTRAINT [FK_ProjectStageDetail_To_AutomationType] FOREIGN KEY ([AutomationTypeId]) REFERENCES [dbo].[AutomationType] ([AutomationTypeId]),
    CONSTRAINT [FK_ProjectStageDetail_To_ProjectDecision] FOREIGN KEY ([ProjectDecisionId]) REFERENCES [dbo].[ProjectDecision] ([ProjectDecisionId]),
    CONSTRAINT [FK_ProjectStageDetail_To_ProjectDetail] FOREIGN KEY ([ProjectDetailId]) REFERENCES [dbo].[ProjectDetail] ([ProjectDetailId]),
    CONSTRAINT [FK_ProjectStageDetail_To_Solution] FOREIGN KEY ([SolutionId]) REFERENCES [dbo].[Solution] ([SolutionId]),
    CONSTRAINT [FK_ProjectStageDetail_To_User_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_ProjectStageDetail_To_user_ModiifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[User] ([UserId])
);

