CREATE TABLE [dbo].[ProjectSupplierDetail] (
    [ProjectSupplierDetailId] BIGINT             IDENTITY (1, 1) NOT NULL,
    [SupplierId]              BIGINT             NOT NULL,
    [ProjectDetailId]         BIGINT             NOT NULL,
    [SupplierContactPerson]   VARCHAR (100)      NULL,
    [SupplierContactNumber]   VARCHAR (100)      NULL,
    [SupplierContactEmail]    VARCHAR (100)      NULL,
    [FirstQuoteRecevedDate]   DATETIMEOFFSET (7) NULL,
    [LastQuoteRecevedDate]    DATETIMEOFFSET (7) NULL,
    [QuoteRevisionId]         BIGINT             NOT NULL,
    [RFQIssueDate]            DATETIMEOFFSET (7) NULL,
    [FirstQuoteAmount]        DECIMAL (18)       NULL,
    [LastQuoteAmount]         DECIMAL (18)       NULL,
    [LaborEstimate]           DECIMAL (18)       NOT NULL,
    [TotalBRC35Project]       DECIMAL (18)       NULL,
    [TOTALBRC]                DECIMAL (18)       NULL,
    [TotalBRC70Project]       DECIMAL (18)       NULL,
    [FinalAmount]             DECIMAL (18)       NULL,
    [IsProjectAwarded]        BIT                NULL,
    [RecordStatus]            CHAR (1)           NOT NULL,
    [CreatedBy]               BIGINT             NOT NULL,
    [CreatedDate]             DATETIMEOFFSET (7) NOT NULL,
    [ModifiedBy]              BIGINT             NOT NULL,
    [ModifiedDate]            DATETIMEOFFSET (7) NOT NULL,
    PRIMARY KEY CLUSTERED ([ProjectSupplierDetailId] ASC),
    CONSTRAINT [FK_ProjectSupplierDetail_To_ProjectDetail] FOREIGN KEY ([ProjectDetailId]) REFERENCES [dbo].[ProjectDetail] ([ProjectDetailId]),
    CONSTRAINT [FK_ProjectSupplierDetail_To_QuoteRevision] FOREIGN KEY ([QuoteRevisionId]) REFERENCES [dbo].[QuoteRevision] ([QuoteRevisionId]),
    CONSTRAINT [FK_ProjectSupplierDetail_To_Supplier] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Supplier] ([SupplierId]),
    CONSTRAINT [FK_ProjectSupplierDetail_To_User_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_ProjectSupplierDetail_To_user_ModiifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[User] ([UserId])
);

