CREATE TABLE [dbo].[ProjectDetail] (
    [ProjectDetailId]    BIGINT             IDENTITY (1, 1) NOT NULL,
    [ProjectNumber]      VARCHAR (100)      NOT NULL,
    [ActualUserId]       BIGINT             NOT NULL,
    [ProjectName]        VARCHAR (400)      NOT NULL,
    [ProjectDescription] VARCHAR (1000)     NOT NULL,
    [CustomerId]         BIGINT             NOT NULL,
    [SegmentId]          BIGINT             NOT NULL,
    [RegionId]           BIGINT             NOT NULL,
    [CategoryId]         BIGINT             NOT NULL,
    [SubcategoryId]      BIGINT             NOT NULL,
    [CountryId]          BIGINT             NOT NULL,
    [SiteId]             BIGINT             NOT NULL,
    [StageId]            BIGINT             NOT NULL,
    [BuildingName]       VARCHAR (100)      NULL,
    [BUleadADID]         VARCHAR (50)       NULL,
    [BUleadEmail]        VARCHAR (200)      NULL,
    [BUleadName]         VARCHAR (200)      NULL,
    [RecordStatus]       CHAR (1)           NOT NULL,
    [CreatedBy]          BIGINT             NOT NULL,
    [CreatedDate]        DATETIMEOFFSET (7) NOT NULL,
    [ModifiedBy]         BIGINT             NOT NULL,
    [ModifiedDate]       DATETIMEOFFSET (7) NOT NULL,
    PRIMARY KEY CLUSTERED ([ProjectDetailId] ASC),
    CONSTRAINT [FK_ProjectDetail_To_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Category] ([CategoryId]),
    CONSTRAINT [FK_ProjectDetail_To_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([CountryId]),
    CONSTRAINT [FK_ProjectDetail_To_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([CustomerId]),
    CONSTRAINT [FK_ProjectDetail_To_Region] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Region] ([RegionId]),
    CONSTRAINT [FK_ProjectDetail_To_Segment] FOREIGN KEY ([SegmentId]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_ProjectDetail_To_Site] FOREIGN KEY ([SiteId]) REFERENCES [dbo].[Site] ([SiteId]),
    CONSTRAINT [FK_ProjectDetail_To_Stage] FOREIGN KEY ([StageId]) REFERENCES [dbo].[Stage] ([StageId]),
    CONSTRAINT [FK_ProjectDetail_To_Subcategory] FOREIGN KEY ([SubcategoryId]) REFERENCES [dbo].[SubCategory] ([SubCategoryId]),
    CONSTRAINT [FK_ProjectDetail_To_User] FOREIGN KEY ([ActualUserId]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_ProjectDetail_To_User_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_ProjectDetail_To_user_ModiifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[User] ([UserId])
);

